### ISSUE TITLE
scapy-real - What should we do of it

### ISSUE THREAD

**Issue by gpotter2** [secdev/scapy-real#1]
Hello,
@p-l- @guedou @hellais @graingert @habnabit

It appears that you are all maintainers of https://pypi.org/project/scapy-real/

The named project appears to be an old forgotten clone of scapy, which had some features that were missing at a time from secdev/scapy. However, we have merged all the missing features in scapy (mostly 802.15.4), meaning this is now outdated.

- First, i wanted to ask if any of you know the historical reasons that lead for such a monster to exist 😄 
- Then what do you think about releasing the current code of this repo as a release (which basically shows a fancy message on installing)

![image](https://user-images.githubusercontent.com/10530980/50376070-172f6d80-0608-11e9-96c7-57edc165938d.png)

There are very few projects using this repo, but they do exist. It would allow to avoid any further confusion. That would break them, but I don't think they are enough for that to be important.

If that doesn't suit you, we also have the following option:
- add scapy as a depedency of scapy-real (but that's kinda ugly), and raise a warning

Thanks a lot for your time.

Edit: FTR
https://github.com/andresriancho/w3af/commit/002be4a501f301f796c72590e5b5eff1c77aef2d
(w3af used it for a while)

**Comment by guedou** [comment]
According to github search, only one repository is referencing scapy-real. I opened an issue to warn the maintainer (see https://github.com/JimJiangX/mimic/issues/1).

I think that it is safe to remove the `scapy-real` repository.

**Comment by graingert** [comment]
It might be worth transfering the PyPI name to the scapy maintenance team

**Comment by gpotter2** [comment]
> It might be worth transfering the PyPI name to the scapy maintenance team

That's already the case.

> I think that it is safe to remove the `scapy-real` repository.

I'd rather not leave the name free, as it's still around on [some blogs](https://zuhdi.org/installing-w3af/). That's why I proposed to upload the content of this repo instead. All the people I mentionned have the permissions to push on PyPI

**Comment by guedou** [comment]
@gpotter2 yes, you can release the code from this repository. It is a good solution.

**Comment by gpotter2** [comment]
@guedou has published the killer version at https://pypi.org/project/scapy-real/
The package is not usable anymore.

This issue will be closed, thanks to all for your help !
